name: otium

on: 
  push:
    branches: [main]
    
env:
  DOTNET_CLI_HOME: /temp
  REPOSITORY: Otium

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        dotnet: ["6.0.X"]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Fetch
        run: cd /root/work/Otium/Otium && git fetch
        
      - name: Pull
        run: cd /root/work/Otium/Otium && git pull

      - name: Install dependencies
        run: cd /root/work/Otium/Otium && dotnet restore

      - name: Build
        run: cd /root/work/Otium/Otium && dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: cd /root/work/Otium/Otium && dotnet publish -c Release -o /root/work/Otium/Otium/Release
        
      - name: Restart the service
        run: |
          systemctl restart otiumbuild.service
          
      - name: Get jobs id from the workflow run
        uses: octokit/request-action@v2.x
        id: get_jobs_id
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{id}/jobs
          owner: ${{ github.repository_owner }}
          repo: ${{ env.REPOSITORY }}
          id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
      
      - name: Export jobs id and conclusi
        run: |
          echo 'JOB_ID_1=${{ fromJson(steps.get_jobs_id.outputs.data).jobs[0].id }}' >> $GITHUB_ENV
          echo 'JOB_CONCLUSION_1=${{ fromJson(steps.get_jobs_id.outputs.data).jobs[0].conclusion }}' >> $GITHUB_ENV
          
      - name: Send a notification to telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Build Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            Build Summary:
              * [${{ env.JOB_CONCLUSION_1 }}] pre-action-stage: ${{ github.server_url }}/${{ github.repository }}/runs/${{ env.JOB_ID_1 }}?check_suite_focus=true
              * [success] post-action-stage: success - ${{ github.server_url }}/${{ github.repository }}/runs/${{ env.JOB_ID_3 }}?check_suite_focus=true
    
