name: otium

on: 
  push:
    branches: [main]
    
env:
  DOTNET_CLI_HOME: /temp

jobs:
  deploy:
    runs-on: self-hosted
    
    strategy:
      matrix:
        dotnet: ["6.0.X"]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Fetch
        run: cd /root/work/Otium/Otium && git fetch
        
      - name: Pull
        run: cd /root/work/Otium/Otium && git pull

      - name: Install dependencies
        run: cd /root/work/Otium/Otium && dotnet restore

      - name: Build
        run: cd /root/work/Otium/Otium && dotnet build --configuration Release --no-restore
        
      - name: Publish
        run: cd /root/work/Otium/Otium && dotnet publish -c Release -o /root/work/Otium/Otium/Release
        
      - name: Restart the service
        run: |
          systemctl restart otiumbuild.service
          
      - name: Send a notification to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Actions.
    
